### ISSUE TITLE
Page 2

### ISSUE THREAD

**Issue by polysa** [lizardmedia/all-products-listing-magento2#6]
Hello and thank you for this useful module.

I am facing the following problem. When trying to load page 2 the load fails.

My dev page is: https://mrb2.ced-dev.com/catalog_all/index/index

When I try to load page 2 the page https://mrb2.ced-dev.com/catalog_all/index/index/?p=2 is loading in order to work we need to load https://mrb2.ced-dev.com/catalog_all/index/index?p=2. 

any help on how to fix this problem?
Thank you in advance.

**Comment by bartoszkubicki** [comment]
@polysa Can you tell what is your magento version?

**Comment by polysa** [comment]
I am using 2.3.4

**Comment by bartoszkubicki** [comment]
@polysa I have this extension working on production and paging is built in way that doesn't work for you. Although I will test it on clean magento (2.3.4 or 2.3.5)

**Comment by polysa** [comment]
@bartoszkubicki

Thank you can check my dev environment here:[Demo]( https://mrb2.ced-dev.com/catalog_all/index/index)

**Comment by bartoszkubicki** [comment]
@polysa I have just tested module on magento 2.3.5 and I can't reproduce this situation. I have it like <domain>/catalog_all/index/index/?p=2
